compiler:
  solc:
    version: 0.8.0
    remappings:
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.2.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.2.0