# Generated by Django 3.1.7 on 2021-11-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraising', '0002_auto_20211107_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='requestID',
            field=models.IntegerField(default=0),
        ),
    ]
